version: '3.8'

services:
  build-service:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./bin:/app/bin  # Binde das Host-Verzeichnis an den Container
    command: ["npm", "run", "build"]  # F체hre den Build-Prozess aus

# Optionaler zus채tzlicher Dienst f체r die Kompilierung
# ohne dass der Container dauerhaft l채uft
  build:
    image: build-service  # Verwende das bereits gebaute Image
    volumes:
      - ./bin:/app/bin  # Binde das Host-Verzeichnis an den Container
    command: ["npm", "run", "build"]
